import type { ShaderGradientInput, ShaderGradientPreset, ShaderGradientPresetName } from './types'

// Baseline for every preset. Anything a preset doesn't specify falls back to
// these values instead of leaking in from the previously applied preset. This
// keeps `preset` calls fully self-contained — picking a preset resets every
// visual field to a known state.
export const BASE_PRESET_PROPS: Partial<ShaderGradientInput> = {
  type: 'plane',
  shader: 'defaults',
  animate: 'on',
  uTime: 0,
  uSpeed: 0.4,
  uStrength: 4,
  uDensity: 1.3,
  uFrequency: 5.5,
  uAmplitude: 1,
  range: 'disabled',
  rangeStart: 0,
  rangeEnd: 40,
  loop: 'off',
  loopDuration: 8,
  positionX: 0,
  positionY: 0,
  positionZ: 0,
  rotationX: 0,
  rotationY: 0,
  rotationZ: 0,
  colors: ['#ff5005', '#dbba95', '#d0bce1'],
  reflection: 0.1,
  wireframe: false,
  cAzimuthAngle: 180,
  cPolarAngle: 90,
  cDistance: 3.6,
  cameraZoom: 1,
  fov: 45,
  lightType: '3d',
  brightness: 1.2,
  envPreset: 'city',
  grain: 'off',
  grainBlending: 1,
  bloom: 'off',
  bloomStrength: 0.6,
  bloomRadius: 0.5,
  bloomThreshold: 0.4,
  vignette: 'off',
  vignetteStrength: 0.8,
  vignetteSoftness: 0.6,
  chromaticAberration: 'off',
  chromaticAberrationStrength: 0.004,
  toggleAxis: false,
  zoomOut: false,
}

const rawPresets: Record<ShaderGradientPresetName, ShaderGradientPreset> = {
  halo: {
    title: 'Halo',
    color: 'white',
    props: {
      type: 'plane',
      shader: 'defaults',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.4,
      uStrength: 4,
      uDensity: 1.3,
      uFrequency: 5.5,
      uAmplitude: 1,
      range: 'disabled',
      rangeStart: 0,
      rangeEnd: 40,
      positionX: -1.4,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 10,
      rotationZ: 50,
      colors: ['#ff5005', '#dbba95', '#d0bce1'],
      reflection: 0.1,
      cAzimuthAngle: 180,
      cDistance: 3.6,
      cPolarAngle: 90,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.2,
      envPreset: 'city',
      grain: 'on',
    },
  },
  pensive: {
    title: 'Pensive',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'defaults',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.3,
      uStrength: 0.4,
      uDensity: 0.8,
      uFrequency: 5.5,
      uAmplitude: 7,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 140,
      colors: ['#809bd6', '#910aff', '#af38ff'],
      reflection: 0.5,
      cAzimuthAngle: 250,
      cDistance: 1.5,
      cPolarAngle: 140,
      cameraZoom: 12.5,
      lightType: '3d',
      brightness: 1.5,
      envPreset: 'city',
      grain: 'on',
    },
  },
  neutronStar: {
    title: 'Neutron Star',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'glass',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.29,
      uStrength: 2.4,
      uDensity: 0.2,
      uFrequency: 5.5,
      uAmplitude: 4.2,
      range: 'disabled',
      rangeStart: 0,
      rangeEnd: 40,
      loop: 'off',
      loopDuration: 8,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 140,
      colors: ['#809bd6', '#910aff', '#af38ff'],
      reflection: 0.4,
      wireframe: false,
      cAzimuthAngle: 317,
      cPolarAngle: 62,
      cDistance: 25.92,
      cameraZoom: 14.58,
      fov: 45,
      lightType: '3d',
      brightness: 2.15,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 1,
      toggleAxis: false,
      pixelDensity: 1.5,
      preserveDrawingBuffer: false,
    },
  },
  mint: {
    title: 'Mint',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'defaults',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.2,
      uStrength: 3.4,
      uDensity: 1.2,
      uFrequency: 0,
      uAmplitude: 0,
      positionX: 0,
      positionY: 0.9,
      positionZ: -0.3,
      rotationX: 45,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#94ffd1', '#6bf5ff', '#ffffff'],
      reflection: 0.1,
      cAzimuthAngle: 170,
      cDistance: 4.4,
      cPolarAngle: 70,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.2,
      envPreset: 'city',
      grain: 'off',
    },
  },
  interstella: {
    title: 'Interstella',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'defaults',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.3,
      uStrength: 0.3,
      uDensity: 0.8,
      uFrequency: 5.5,
      uAmplitude: 3.2,
      positionX: -0.1,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 130,
      rotationZ: 70,
      colors: ['#73bfc4', '#ff810a', '#8da0ce'],
      reflection: 0.4,
      cAzimuthAngle: 270,
      cDistance: 0.5,
      cPolarAngle: 180,
      cameraZoom: 15.1,
      lightType: 'env',
      brightness: 0.8,
      envPreset: 'city',
      grain: 'on',
    },
  },
  nightyNight: {
    title: 'Nighty Night',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'defaults',
      animate: 'on',
      uTime: 8,
      uSpeed: 0.3,
      uStrength: 1.5,
      uDensity: 1.5,
      uFrequency: 0,
      uAmplitude: 0,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 50,
      rotationY: 0,
      rotationZ: -60,
      colors: ['#606080', '#8d7dca', '#212121'],
      reflection: 0.1,
      cAzimuthAngle: 180,
      cDistance: 2.8,
      cPolarAngle: 80,
      cameraZoom: 9.1,
      lightType: '3d',
      brightness: 1,
      envPreset: 'city',
      grain: 'on',
    },
  },
  violaOrientalis: {
    title: 'Viola',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'defaults',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.1,
      uStrength: 1,
      uDensity: 1.1,
      uFrequency: 5.5,
      uAmplitude: 1.4,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#ffffff', '#ffbb00', '#0700ff'],
      reflection: 0.1,
      cAzimuthAngle: 0,
      cDistance: 7.1,
      cPolarAngle: 140,
      cameraZoom: 17.3,
      lightType: '3d',
      brightness: 1.1,
      envPreset: 'city',
      grain: 'off',
    },
  },
  universe: {
    title: 'Universe',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'defaults',
      animate: 'on',
      uTime: 0.2,
      uSpeed: 0.1,
      uStrength: 2.4,
      uDensity: 1.1,
      uFrequency: 5.5,
      uAmplitude: 0,
      positionX: -0.5,
      positionY: 0.1,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 235,
      colors: ['#5606ff', '#fe8989', '#000000'],
      reflection: 0.1,
      cAzimuthAngle: 180,
      cDistance: 3.9,
      cPolarAngle: 115,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.1,
      envPreset: 'city',
      grain: 'off',
    },
  },
  sunset: {
    title: 'Sunset',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'defaults',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.1,
      uStrength: 0.4,
      uDensity: 1.1,
      uFrequency: 5.5,
      uAmplitude: 1.4,
      positionX: 0,
      positionY: -0.15,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#ff7a33', '#33a0ff', '#ffc53d'],
      reflection: 0.1,
      cAzimuthAngle: 60,
      cDistance: 7.1,
      cPolarAngle: 90,
      cameraZoom: 15.3,
      lightType: '3d',
      brightness: 1.5,
      envPreset: 'dawn',
      grain: 'off',
    },
  },
  mandarin: {
    title: 'Mandarin',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'defaults',
      animate: 'on',
      uTime: 0.2,
      uSpeed: 0.2,
      uStrength: 3,
      uDensity: 1.8,
      uFrequency: 5.5,
      uAmplitude: 0,
      positionX: 0,
      positionY: -2.1,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 225,
      colors: ['#ff6a1a', '#c73c00', '#fd4912'],
      reflection: 0.1,
      cAzimuthAngle: 180,
      cDistance: 2.4,
      cPolarAngle: 95,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.2,
      envPreset: 'city',
      grain: 'off',
    },
  },
  cottonCandy: {
    title: 'Cotton Candy',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'defaults',
      animate: 'on',
      uTime: 0.2,
      uSpeed: 0.3,
      uStrength: 3,
      uDensity: 1,
      uFrequency: 5.5,
      uAmplitude: 0,
      positionX: 0,
      positionY: 1.8,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: -90,
      colors: ['#ebedff', '#f3f2f8', '#dbf8ff'],
      reflection: 0.1,
      cAzimuthAngle: 180,
      cDistance: 2.9,
      cPolarAngle: 120,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.2,
      envPreset: 'city',
      grain: 'off',
    },
  },
  lavaFlow: {
    title: 'Lava Flow',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'lava',
      animate: 'on',
      uTime: 8,
      uSpeed: 0.32,
      uStrength: 1.1,
      uDensity: 1.3,
      uFrequency: 0,
      uAmplitude: 2.2,
      range: 'disabled',
      rangeStart: 0,
      rangeEnd: 40,
      loop: 'off',
      loopDuration: 8,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 50,
      rotationY: 0,
      rotationZ: -60,
      colors: ['#770e69', '#830101', '#ae2424'],
      reflection: 0.4,
      wireframe: false,
      cAzimuthAngle: 366,
      cPolarAngle: 156,
      cDistance: 2.96,
      cameraZoom: 2.14,
      fov: 45,
      lightType: '3d',
      brightness: 1,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 1,
      toggleAxis: false,
      pixelDensity: 1.5,
      preserveDrawingBuffer: false,
    },
  },
  borealis: {
    title: 'Borealis',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'aurora',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.25,
      uStrength: 2.8,
      uDensity: 1.0,
      uFrequency: 3.5,
      uAmplitude: 1.5,
      positionX: 0,
      positionY: 0.6,
      positionZ: -0.2,
      rotationX: 40,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#00ff87', '#60efff', '#7b2fbe'],
      reflection: 0.15,
      cAzimuthAngle: 180,
      cDistance: 3.8,
      cPolarAngle: 75,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.3,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 0.8,
    },
  },
  deepOcean: {
    title: 'Deep Ocean',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'aurora',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.15,
      uStrength: 1.8,
      uDensity: 0.9,
      uFrequency: 4.0,
      uAmplitude: 2.5,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 120,
      colors: ['#003366', '#00b4d8', '#0ef5a0'],
      reflection: 0.4,
      cAzimuthAngle: 200,
      cDistance: 1.8,
      cPolarAngle: 110,
      cameraZoom: 13.5,
      lightType: '3d',
      brightness: 1.4,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 0.6,
    },
  },
  silkRoad: {
    title: 'Silk Road',
    color: 'white',
    props: {
      type: 'plane',
      shader: 'marble',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.08,
      uStrength: 2.0,
      uDensity: 1.2,
      uFrequency: 3.0,
      uAmplitude: 0.8,
      positionX: -1.2,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 15,
      rotationZ: 40,
      colors: ['#f5f0e8', '#c9a96e', '#2c1810'],
      reflection: 0.3,
      cAzimuthAngle: 180,
      cDistance: 3.2,
      cPolarAngle: 85,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.5,
      envPreset: 'lobby',
      grain: 'off',
    },
  },
  jade: {
    title: 'Jade',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'marble',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.06,
      uStrength: 0.8,
      uDensity: 1.0,
      uFrequency: 4.0,
      uAmplitude: 1.2,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#1a6b3c', '#8fd9a8', '#0a3d1f'],
      reflection: 0.5,
      cAzimuthAngle: 40,
      cDistance: 6.5,
      cPolarAngle: 100,
      cameraZoom: 16.0,
      lightType: '3d',
      brightness: 1.6,
      envPreset: 'lobby',
      grain: 'off',
    },
  },
  neonGrid: {
    title: 'Neon Grid',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'pulse',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.4,
      uStrength: 1.6,
      uDensity: 1.5,
      uFrequency: 5.0,
      uAmplitude: 1.8,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 50,
      rotationY: 0,
      rotationZ: -45,
      colors: ['#ff00ff', '#00ffff', '#0a0a2e'],
      reflection: 0.2,
      cAzimuthAngle: 180,
      cDistance: 3.0,
      cPolarAngle: 80,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.1,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 1.0,
    },
  },
  heartbeat: {
    title: 'Heartbeat',
    color: 'white',
    props: {
      type: 'sphere',
      shader: 'pulse',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.35,
      uStrength: 1.2,
      uDensity: 0.8,
      uFrequency: 5.5,
      uAmplitude: 3.0,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 160,
      colors: ['#ff1744', '#ff80ab', '#1a0005'],
      reflection: 0.35,
      cAzimuthAngle: 280,
      cDistance: 2.0,
      cPolarAngle: 90,
      cameraZoom: 14.0,
      lightType: '3d',
      brightness: 1.3,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 0.7,
    },
  },
  chromatic: {
    title: 'Chromatic',
    color: 'white',
    props: {
      type: 'waterPlane',
      shader: 'spectrum',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.28,
      uStrength: 1.6,
      uDensity: 1.2,
      uFrequency: 4.5,
      uAmplitude: 1.6,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 45,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#ff2b4d', '#ff9544', '#ffe14e', '#30e890', '#2bb7ff', '#6658ff', '#c742ff'],
      reflection: 0.2,
      cAzimuthAngle: 180,
      cPolarAngle: 80,
      cDistance: 3.2,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.2,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 0.45,
    },
  },
  clubLights: {
    title: 'Club Lights',
    color: 'white',
    props: {
      type: 'plane',
      shader: 'halo',
      animate: 'on',
      uTime: 0,
      uSpeed: 0.55,
      uStrength: 1.5,
      uDensity: 1.6,
      uFrequency: 7.0,
      uAmplitude: 0.6,
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      colors: ['#c84bff', '#38f4c7', '#ff4e9a'],
      reflection: 0,
      cAzimuthAngle: 180,
      cPolarAngle: 90,
      cDistance: 3.4,
      cameraZoom: 1,
      lightType: '3d',
      brightness: 1.1,
      envPreset: 'city',
      grain: 'on',
      grainBlending: 0.3,
    },
  },
}

export const presets: Record<ShaderGradientPresetName, ShaderGradientPreset> = Object.fromEntries(
  (Object.entries(rawPresets) as [ShaderGradientPresetName, ShaderGradientPreset][]).map(
    ([name, preset]) => [
      name,
      { ...preset, props: { ...BASE_PRESET_PROPS, ...preset.props } },
    ],
  ),
) as Record<ShaderGradientPresetName, ShaderGradientPreset>

export const presetEntries = Object.entries(presets) as [ShaderGradientPresetName, ShaderGradientPreset][]
